# for local development
version: '3.9'
services:
  go-rest-api:
    image: "golang:1.21.5-bookworm"
    restart: on-failure
    ports:
      -  "8080:8080/tcp"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      mysql:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    environment:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOFLAGS=-mod=vendor
    env_file:
      - .env
    command: /bin/bash -c  "git config --global --add safe.directory /app && make build/restapi && ./build/restapi"
  db-migration:
    image: "amacneil/dbmate:2.9"
    restart: "on-failure"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      mysql:
        condition: service_started
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/dev-api-fd
      - DBMATE_MIGRATIONS_DIR=/app/resources/mysql/migrations
      - DBMATE_NO_DUMP_SCHEMA=true
      - DBMATE_VERBOSE=true
      - DBMATE_STRICT=true
      - DBMATE_WAIT=true
      - DBMATE_WAIT_TIMEOUT=60s
    command: up
   # ------------------------------------------ DB BROWSER WEB APP ------------------------------------------
  adminer:
    container_name: adminer
    image: adminer:4-standalone
    restart: on-failure
    depends_on:
      mysql:
        condition: service_started
    ports:
      - "8888:8080/tcp"
 # ------------------------------------------ INFRASTRUCTURES ------------------------------------------
  mysql:
    container_name: mysql
    image: mysql:8.0-debian
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev-api-fd
volumes:
  mysql-data:
