openapi: 3.1.0
info:
  title: Auth Service rizkysr90pos - OpenAPI 3.0
  description: |-
    This is microservice for auth service
  contact:
    email: rizkysr90@gmail.com
  version: 1.0.0
tags:
  - name: Auth Microservices
    description: Everything about your auth service
  - name: Stores
    description: Everything about store service
paths:
  /api/v1/auth/users:
    post:
      tags:
        - Users
      summary: Create new users
      description: Create new users that with unique email
      operationId: users.create
      requestBody:
        content:
          application/json:
            schema:
              required:
                - first_name
                - last_name
                - email
                - password
                - confirm_password
              type: object
              properties:
                first_name:
                  type: string
                  description: first name of new user
                last_name:
                  type: string
                  description: last name of new user
                email:
                  type: string
                  description: email of new user
                password:
                  type: string
                  description: password of new user
                confirm_password:
                  type: string
                  description: to validate inputted password
        required: true
      responses:
        "201":
          description: Successful to create new user
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Provided data doesn't meet the validation
  /api/v1/auth/users/login:
    post:
      tags:
        - Users
      summary: Login users
      description: Login registered users
      operationId: users.login
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
                - password
              type: object
              properties:
                email:
                  type: string
                  description: email of the user
                password:
                  type: string
                  description: password of the user
        required: true
      responses:
        "200":
          description: Success login
          headers:
            Set-Cookie:
              description: Cookie returned in the response
              schema:
                type: array
                items:
                  type: string
                examples:
                  - "access_token=cookie1_value;"
                  - "refresh_token=cookie2_value;"

        "400":
          description: Provided data doesn't meet the validation
  /api/v1/auth/users/refreshtoken:
    post:
      tags:
        - Users
      summary: To refresh the access token
      description: using refresh token to get new access token
      operationId: users.refreshtoken
      parameters:
        - in: cookie
          name: refresh_token
          required: true
          schema:
            type: string
          description: refresh_token value
      responses:
        "200":
          description: Success to get a new refresh token
          headers:
            Set-Cookie:
              description: Cookie returned in the response
              schema:
                type: array
                items:
                  type: string
                examples:
                  - "access_token=cookie1_value;"

        "400":
          description: Provided data doesn't meet the validation

  /api/v1/stores:
    post:
      tags:
        - Stores
      summary: To create store
      operationId: stores.create
      parameters:
        - in: cookie
          name: access_token
          required: true
          schema:
            type: string
          description: access_token value
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - address
                - contact
              type: object
              properties:
                name:
                  type: string
                  description: name of the store
                address:
                  type: string
                  description: address of the store
                contact:
                  type: string
                  description: contact of the store
        required: true
      responses:
        "201":
          description: Successful to create new user
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Provided data doesn't meet the validation
  # securitySchemes:
  #   petstore_auth:
  #     type: oauth2
  #     flows:
  #       implicit:
  #         authorizationUrl: https://petstore3.swagger.io/oauth/authorize
  #         scopes:
  #           write:pets: modify pets in your account
  #           read:pets: read your pets
  #   api_key:
  #     type: apiKey
  #     name: api_key
  #     in: header
