// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/branches": {
            "get": {
                "description": "Retrieves a paginated list of branches with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branches"
                ],
                "summary": "Get Branches",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page size (default: 20)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page_number",
                        "in": "query"
                    },
                    {
                        "maxLength": 100,
                        "type": "string",
                        "description": "Branch name filter",
                        "name": "branch_name",
                        "in": "query"
                    },
                    {
                        "maxLength": 500,
                        "type": "string",
                        "description": "Tenant ID filter",
                        "name": "tenant_id",
                        "in": "query"
                    },
                    {
                        "maxLength": 500,
                        "type": "string",
                        "description": "User performing the action",
                        "name": "action_by",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved branches",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_service_branches.ResponseGetBranches"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new branch with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branches"
                ],
                "summary": "Create Branch",
                "parameters": [
                    {
                        "description": "Branch creation details",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_service_branches.RequestCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Branch created successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/products/{product_id}": {
            "get": {
                "description": "Retrieve a single product's details by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResGetProductByID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing product's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product information to update",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ReqUpdateProduct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResUpdateProduct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a product by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResDeleteProductByID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/roles": {
            "post": {
                "description": "Creates a new role with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Create Role",
                "parameters": [
                    {
                        "description": "Role creation request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_service_roles.RequestCreateRoles"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Role created successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "post": {
                "description": "Creates a new user with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "User creation request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_service_admin.RequestCreateAdmin"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/auth/owner/login": {
            "get": {
                "description": "Initiates the OAuth login flow for owners",
                "tags": [
                    "Authentication"
                ],
                "summary": "Owner Login",
                "responses": {
                    "302": {
                        "description": "Redirect to OAuth provider",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/auth/register/owner": {
            "get": {
                "description": "Initiates owner registration process and redirects to OAuth authorization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register owner for a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant name to register owner for",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to OAuth authorization URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Retrieve all categories with optional pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get all categories",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (default: 1)",
                        "name": "page_number",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Page size (default: 20)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResGetAllCategory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new category with the provided name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "description": "Category to create",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ReqCreateCategory"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResCreateCategory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/categories/{category_id}": {
            "get": {
                "description": "Retrieve a specific category by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get a category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResGetCategoryByID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a specific category's name by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Edit a category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated category information",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ReqUpdateCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResUpdateCategory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific category by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Delete a category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResDeleteCategory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Retrieve a list of products with optional filtering and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get all products",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category ID to filter products",
                        "name": "category_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResGetAllProducts"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new product with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "description": "Product details",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ReqCreateProduct"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.ResCreateProduct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        },
        "/products/generate-barcode": {
            "post": {
                "description": "Generate a PDF containing barcodes for a single product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Generate barcode PDF for a single product",
                "parameters": [
                    {
                        "description": "Product ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_internal_payload.GenerateBarcodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rizkysr90-pos_internal_payload.CategoryData": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_payload.GenerateBarcodeRequest": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_payload.Pagination": {
            "type": "object",
            "properties": {
                "page_number": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_elements": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ProductData": {
            "type": "object",
            "properties": {
                "base_price": {
                    "type": "number"
                },
                "category_id": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "stock_quantity": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ReqCreateCategory": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ReqCreateProduct": {
            "type": "object",
            "required": [
                "category_id",
                "product_name"
            ],
            "properties": {
                "base_price": {
                    "type": "number",
                    "minimum": 0
                },
                "category_id": {
                    "type": "string"
                },
                "price": {
                    "type": "number",
                    "minimum": 0
                },
                "product_name": {
                    "type": "string",
                    "maxLength": 40
                },
                "stock_quantity": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "rizkysr90-pos_internal_payload.ReqUpdateCategory": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ReqUpdateProduct": {
            "type": "object",
            "required": [
                "category_id",
                "product_id",
                "product_name"
            ],
            "properties": {
                "base_price": {
                    "type": "number",
                    "minimum": 0
                },
                "category_id": {
                    "type": "string"
                },
                "price": {
                    "type": "number",
                    "minimum": 0
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string",
                    "maxLength": 40
                },
                "stock_quantity": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "rizkysr90-pos_internal_payload.ResCreateCategory": {
            "type": "object"
        },
        "rizkysr90-pos_internal_payload.ResCreateProduct": {
            "type": "object"
        },
        "rizkysr90-pos_internal_payload.ResDeleteCategory": {
            "type": "object"
        },
        "rizkysr90-pos_internal_payload.ResDeleteProductByID": {
            "type": "object"
        },
        "rizkysr90-pos_internal_payload.ResGetAllCategory": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rizkysr90-pos_internal_payload.CategoryData"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/rizkysr90-pos_internal_payload.Pagination"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ResGetAllProducts": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rizkysr90-pos_internal_payload.ProductData"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/rizkysr90-pos_internal_payload.Pagination"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ResGetCategoryByID": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/rizkysr90-pos_internal_payload.CategoryData"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ResGetProductByID": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/rizkysr90-pos_internal_payload.ProductData"
                }
            }
        },
        "rizkysr90-pos_internal_payload.ResUpdateCategory": {
            "type": "object"
        },
        "rizkysr90-pos_internal_payload.ResUpdateProduct": {
            "type": "object"
        },
        "rizkysr90-pos_internal_service_admin.RequestCreateAdmin": {
            "description": "Request body for creating a new admin user",
            "type": "object",
            "required": [
                "action_by",
                "email",
                "password",
                "tenant_id",
                "user_type"
            ],
            "properties": {
                "action_by": {
                    "description": "ID of the user performing the action\nRequired: true\nMax Length: 100\nMin Length: 1",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "branch_id": {
                    "description": "Branch ID - UUID of the branch where the user will be assigned\nRequired: true when user_type is BRANCH, optional otherwise\nMax Length: 500\nFormat: uuid\nExample: 550e8400-e29b-41d4-a716-446655440000\nNote: Must be a valid UUID of an existing branch in the system. Required when creating branch users.",
                    "type": "string",
                    "maxLength": 500,
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "email": {
                    "description": "Email address of the admin user\nRequired: true\nMax Length: 200\nMin Length: 3\nPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 3,
                    "example": "admin@example.com"
                },
                "full_name": {
                    "description": "Full name\nRequired\nMax Length : 255\nExample : Rizki Susilo R",
                    "type": "string",
                    "maxLength": 255,
                    "example": "Rizki Susilo Ramadhan"
                },
                "password": {
                    "description": "Password for the admin user\nRequired: true\nMax Length: 100\nMin Length: 8",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "StrongP@ssw0rd"
                },
                "tenant_id": {
                    "description": "Tenant ID for the admin user\nRequired: true\nMax Length: 500\nMin Length: 1",
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 1,
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "user_type": {
                    "description": "Type of user (ADMIN or BRANCH)\nRequired: true\nEnum: ADMIN,BRANCH",
                    "enum": [
                        "ADMIN",
                        "BRANCH"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/rizkysr90-pos_internal_service_admin.UserType"
                        }
                    ],
                    "example": "ADMIN"
                }
            }
        },
        "rizkysr90-pos_internal_service_admin.UserType": {
            "type": "string",
            "enum": [
                "ADMIN",
                "BRANCH"
            ],
            "x-enum-varnames": [
                "Admin",
                "Branch"
            ]
        },
        "rizkysr90-pos_internal_service_branches.BranchesData": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Branch address\nRequired: false\nExample: Jl. Sudirman No. 123, Jakarta",
                    "type": "string"
                },
                "created_at": {
                    "description": "Creation timestamp\nRequired: true\nExample: 2025-01-11T14:30:00Z",
                    "type": "string"
                },
                "created_by": {
                    "description": "User who created the branch\nRequired: false\nMax Length: 255\nExample: jane.doe@company.com",
                    "type": "string"
                },
                "created_by_owner": {
                    "description": "Owner who created the branch\nRequired: false\nMax Length: 255\nExample: John Doe",
                    "type": "string"
                },
                "id": {
                    "description": "Branch UUID\nRequired: true\nExample: 550e8400-e29b-41d4-a716-446655440000",
                    "type": "string"
                },
                "name": {
                    "description": "Branch name\nRequired: true\nMax Length: 255\nExample: Main Branch Jakarta",
                    "type": "string"
                },
                "tenant_id": {
                    "description": "Tenant UUID\nRequired: true\nExample: 550e8400-e29b-41d4-a716-446655440001",
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_service_branches.RequestCreate": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Physical address of the branch\nRequired: true\nMax Length: 500",
                    "type": "string"
                },
                "branch_name": {
                    "description": "Name of the branch\nRequired: true\nMax Length: 40",
                    "type": "string"
                },
                "created_by": {
                    "description": "ID of the user creating the branch\nRequired: true\nMax Length: 100",
                    "type": "string"
                },
                "tenant_id": {
                    "description": "Tenant ID for the branch\nRequired: true\nMax Length: 500",
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_service_branches.ResponseGetBranches": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rizkysr90-pos_internal_service_branches.BranchesData"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/rizkysr90-pos_internal_store.Pagination"
                }
            }
        },
        "rizkysr90-pos_internal_service_roles.RequestCreateRoles": {
            "type": "object",
            "properties": {
                "action_by": {
                    "description": "ID of the user performing the action\nRequired: true\nMax Length: 100",
                    "type": "string"
                },
                "description": {
                    "description": "Description of the role and its responsibilities\nRequired: true\nMax Length: 500",
                    "type": "string"
                },
                "is_head_office_role": {
                    "description": "Indicates if this is a head office role\nRequired: true\nDefault: false",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name of the role\nRequired: true\nMax Length: 200",
                    "type": "string"
                },
                "tenant_id": {
                    "description": "Tenant ID for the role\nRequired: true\nMax Length: 500",
                    "type": "string"
                }
            }
        },
        "rizkysr90-pos_internal_store.Pagination": {
            "type": "object",
            "properties": {
                "page_number": {
                    "description": "Current page number\nRequired: true\nExample: 1\nMinimum: 1",
                    "type": "integer"
                },
                "page_size": {
                    "description": "Current page size\nRequired: true\nExample: 20\nMinimum: 1",
                    "type": "integer"
                },
                "total_elements": {
                    "description": "Total number of elements\nRequired: true\nExample: 100\nMinimum: 0",
                    "type": "integer"
                },
                "total_pages": {
                    "description": "Total number of pages\nRequired: true\nExample: 5\nMinimum: 0",
                    "type": "integer"
                }
            }
        },
        "rizkysr90-pos_pkg_errorHandler.HttpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "info": {
                    "type": "string"
                },
                "message": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Point of Sale API",
	Description:      "API for Point of Sale System",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
