basePath: /api/v1
definitions:
  rizkysr90-pos_internal_payload.CategoryData:
    properties:
      category_name:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
  rizkysr90-pos_internal_payload.GenerateBarcodeRequest:
    properties:
      product_id:
        type: string
    type: object
  rizkysr90-pos_internal_payload.Pagination:
    properties:
      page_number:
        type: integer
      page_size:
        type: integer
      total_elements:
        type: integer
      total_pages:
        type: integer
    type: object
  rizkysr90-pos_internal_payload.ProductData:
    properties:
      base_price:
        type: number
      category_id:
        type: string
      category_name:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      price:
        type: number
      product_id:
        type: string
      product_name:
        type: string
      stock_quantity:
        type: integer
      updated_at:
        type: string
    type: object
  rizkysr90-pos_internal_payload.ReqCreateCategory:
    properties:
      category_name:
        type: string
    type: object
  rizkysr90-pos_internal_payload.ReqCreateProduct:
    properties:
      base_price:
        minimum: 0
        type: number
      category_id:
        type: string
      price:
        minimum: 0
        type: number
      product_name:
        maxLength: 40
        type: string
      stock_quantity:
        minimum: 0
        type: integer
    required:
    - category_id
    - product_name
    type: object
  rizkysr90-pos_internal_payload.ReqUpdateCategory:
    properties:
      category_name:
        type: string
      id:
        type: string
    type: object
  rizkysr90-pos_internal_payload.ReqUpdateProduct:
    properties:
      base_price:
        minimum: 0
        type: number
      category_id:
        type: string
      price:
        minimum: 0
        type: number
      product_id:
        type: string
      product_name:
        maxLength: 40
        type: string
      stock_quantity:
        minimum: 0
        type: integer
    required:
    - category_id
    - product_id
    - product_name
    type: object
  rizkysr90-pos_internal_payload.ResCreateCategory:
    type: object
  rizkysr90-pos_internal_payload.ResCreateProduct:
    type: object
  rizkysr90-pos_internal_payload.ResDeleteCategory:
    type: object
  rizkysr90-pos_internal_payload.ResDeleteProductByID:
    type: object
  rizkysr90-pos_internal_payload.ResGetAllCategory:
    properties:
      data:
        items:
          $ref: '#/definitions/rizkysr90-pos_internal_payload.CategoryData'
        type: array
      metadata:
        $ref: '#/definitions/rizkysr90-pos_internal_payload.Pagination'
    type: object
  rizkysr90-pos_internal_payload.ResGetAllProducts:
    properties:
      data:
        items:
          $ref: '#/definitions/rizkysr90-pos_internal_payload.ProductData'
        type: array
      metadata:
        $ref: '#/definitions/rizkysr90-pos_internal_payload.Pagination'
    type: object
  rizkysr90-pos_internal_payload.ResGetCategoryByID:
    properties:
      data:
        $ref: '#/definitions/rizkysr90-pos_internal_payload.CategoryData'
    type: object
  rizkysr90-pos_internal_payload.ResGetProductByID:
    properties:
      data:
        $ref: '#/definitions/rizkysr90-pos_internal_payload.ProductData'
    type: object
  rizkysr90-pos_internal_payload.ResUpdateCategory:
    type: object
  rizkysr90-pos_internal_payload.ResUpdateProduct:
    type: object
  rizkysr90-pos_pkg_errorHandler.HttpError:
    properties:
      code:
        type: integer
      info:
        type: string
      message: {}
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Point of Sale System
  title: Point of Sale API
  version: "1.0"
paths:
  /api/v1/products/{product_id}:
    delete:
      consumes:
      - application/json
      description: Delete a product by its ID
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResDeleteProductByID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Retrieve a single product's details by its ID
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResGetProductByID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "404":
          description: Product not found
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Get a product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update an existing product's details
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: string
      - description: Product information to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/rizkysr90-pos_internal_payload.ReqUpdateProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResUpdateProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "404":
          description: Product not found
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Update a product
      tags:
      - products
  /auth/register/owner:
    get:
      consumes:
      - application/json
      description: Initiates owner registration process and redirects to OAuth authorization
      parameters:
      - description: Tenant name to register owner for
        in: query
        name: tenant
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Redirect to OAuth authorization URL
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Register owner for a tenant
      tags:
      - auth
  /categories:
    get:
      consumes:
      - application/json
      description: Retrieve all categories with optional pagination
      parameters:
      - default: 1
        description: 'Page number (default: 1)'
        in: query
        minimum: 1
        name: page_number
        type: integer
      - default: 20
        description: 'Page size (default: 20)'
        in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResGetAllCategory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category with the provided name
      parameters:
      - description: Category to create
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/rizkysr90-pos_internal_payload.ReqCreateCategory'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResCreateCategory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Create a new category
      tags:
      - categories
  /categories/{category_id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific category by its ID
      parameters:
      - description: Category ID
        in: path
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResDeleteCategory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Delete a category
      tags:
      - categories
    get:
      consumes:
      - application/json
      description: Retrieve a specific category by its ID
      parameters:
      - description: Category ID
        in: path
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResGetCategoryByID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Get a category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a specific category's name by its ID
      parameters:
      - description: Category ID
        in: path
        name: category_id
        required: true
        type: string
      - description: Updated category information
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/rizkysr90-pos_internal_payload.ReqUpdateCategory'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResUpdateCategory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Edit a category by ID
      tags:
      - categories
  /products:
    get:
      consumes:
      - application/json
      description: Retrieve a list of products with optional filtering and pagination
      parameters:
      - default: 10
        description: Number of items per page
        in: query
        name: page_size
        type: integer
      - default: 1
        description: Page number
        in: query
        name: page_number
        type: integer
      - description: Category ID to filter products
        in: query
        name: category_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResGetAllProducts'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product with the provided details
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/rizkysr90-pos_internal_payload.ReqCreateProduct'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rizkysr90-pos_internal_payload.ResCreateProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Create a new product
      tags:
      - products
  /products/generate-barcode:
    post:
      consumes:
      - application/json
      description: Generate a PDF containing barcodes for a single product
      parameters:
      - description: Product ID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rizkysr90-pos_internal_payload.GenerateBarcodeRequest'
      produces:
      - application/pdf
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rizkysr90-pos_pkg_errorHandler.HttpError'
      summary: Generate barcode PDF for a single product
      tags:
      - products
swagger: "2.0"
